---
  - name: Install db packages
    yum:
      name: ["mariadb","mariadb-server"]
      state: present
  - name: Enable mariadb service
    service:
      name: mariadb
      state: started
      enabled: yes